### PR TITLE
fix(init-xmcp): support comments and trailing commas in tsconfig.json | Fixes #109

### LINKED ISSUE #109: init-xmcp fails with "Invalid tsconfig.json file" when tsconfig contains comments or trailing commas
### TL;DR

`init-xmcp` fails with a misleading "Invalid tsconfig.json file" error if your `tsconfig.json` contains:

* comments (`//` or `/* */`)
* trailing commas

These are all allowed by TypeScript, but the CLI seems to use `JSON.parse`, which rejects them without a clear message. This is especially common in T3 Stack projects, where commented `tsconfig` files are generated by default.

---
---

### Steps to Reproduce

1. Create a new [T3 Stack](https://create.t3.gg/) project using the official CLI:

   ```bash
   npx create-t3-app@latest my-app
   ```

   Select the following options:

   * App Router
   * TypeScript
   * Next.js (v15)

2. In `tsconfig.json`, add:

   * any `//` or `/* … */` comment
   * or a trailing comma after a property

   Example:

   ```jsonc
   {
     "compilerOptions": {
       "moduleResolution": "Bundler", // ← comment breaks JSON.parse
       "incremental": true,           // ← trailing comma
     }
   }
   ```

3. Run the CLI:

   ```bash
   cd my-app
   npx init-xmcp --yes
   ```

### Current vs. Expected behavior

**Expected**

The CLI should detect a valid TypeScript project and complete the setup.
If the config is invalid, it should at least report a clear parse error (file + line).

**Observed**

```bash
init-xmcp@0.1.7
Please initialize xmcp within a TypeScript project. Invalid tsconfig.json file
```

TypeScript compiles the project fine, but the CLI fails silently if the file contains comments or trailing commas

### Affected Package

init-xmcp

### Provide environment information

```bash
Operating System:
  - OS: macOS 15.2
  - CPU: Apple M4 Pro (12-core, arm64)
  - RAM: 24 GB
  - Shell: zsh 5.9

Binaries:
  - Node: 22.17.1
  - npm: 10.9.2
  - pnpm: 10.14.0

npmPackages:
  - typescript: 5.9.2
  - next: 15.2.3
  - xmcp: 0.1.7

xmcp CLI version: 0.1.7
Adapter: Next.js (via T3 Stack)
```

### Additional context

* The issue came up when trying to use `init-xmcp` in a **T3 Stack** project using Next.js + TypeScript.
* The CLI appears to parse `tsconfig.json` using `JSON.parse`, which does **not** support comments or trailing commas.
* However, TypeScript does allow both, so the project compiles fine but the CLI fails unexpectedly.
Obvio. Te dejo la sección **final mejorada**, con un cierre más piola y empático, manteniendo el tono técnico pero con un toque de comunidad:

---

### Proposal

* Replace `JSON.parse` with `typescript.parseJsonConfigFileContent` or `readJsonConfigFile` to properly support the TypeScript superset syntax (comments, trailing commas, etc.).
* At the very least, surface a meaningful error with line/column and a hint on how to fix it.
* If strict JSON is required by design, clarify that in the docs or warn early with a friendly explanation.

Thanks for the tool and the effort, excited to keep exploring what you're building! <3

### PR DESCRIPTION
**Pull request by bilune**
## Summary

Fix `init-xmcp` to support TypeScript configuration files with comments and trailing commas. This resolves the issue where `init-xmcp` would fail with "Invalid tsconfig.json file" when encountering valid TypeScript syntax that includes comments or trailing commas, which are commonly used in T3 Stack projects and other modern TypeScript setups.

## Type of Change

- [x] Bug fixing
- [ ] Adding a feature
- [ ] Improving documentation
- [ ] Adding or updating examples
- [ ] Performance - bundle size improvement (if applicable)

## Affected Packages

- [ ] `xmcp` (core framework)
- [ ] `create-xmcp-app`
- [x] `init-xmcp`
- [ ] Documentation
- [ ] Examples

### Before (failing)
```bash
init-xmcp@0.1.7
Please initialize xmcp within a TypeScript project. Invalid tsconfig.json file
```

### After (working)
```bash
init-xmcp@0.1.7
✔ xmcp initialized successfully!
```

### Example tsconfig.json that now works
```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "rootDir": "./src", // This comment now works
    "outDir": "./dist", // This trailing comma now works
  },
  "include": [
    "src/**/*.ts" // Comments in arrays work too
  ]
}
```

## Related Issues

Fixes #109

## Technical Details

- **Solution**: Use TypeScript's official API (`ts.readConfigFile`) instead of `JSON.parse`
- **Dependencies**: Added `typescript` as peerDependency (already required in XMCP projects)
- **Files changed**: 
  - `packages/init-xmcp/src/utils/read-config-file.ts` (new helper)
  - `packages/init-xmcp/src/helpers/detect-framework.ts` (use new helper)
  - `packages/init-xmcp/src/helpers/update-tsconfig.ts` (use new helper)
  - `packages/init-xmcp/package.json` (add peerDependency)

This change ensures `init-xmcp` works seamlessly with modern TypeScript projects that use comments and trailing commas in their configuration files, improving the developer experience for T3 Stack and similar projects.

### CODE REVIEW

File: packages/init-xmcp/src/helpers/update-tsconfig.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import path from "path";
 import fs from "fs-extra";
 import chalk from "chalk";
+import { readTsConfigFile } from "../utils/read-config-file.js";
```
Comment (matiasngf) [inline packages/init-xmcp/src/helpers/update-tsconfig.ts:4]: Can we remove the .js from the import?

File: packages/init-xmcp/package.json [hunk 2]
```diff
@@ -48,6 +48,9 @@
     "inquirer": "^9.2.12",
     "ora": "^7.0.1"
   },
+  "peerDependencies": {
+    "typescript": "^5.0.0"
```
Comment (matiasngf) [inline packages/init-xmcp/package.json:52]: I need to test it but does it making this a peerDependency will require the user tu manually install typescript globally?

**Review by matiasngf — CHANGES_REQUESTED** [review]
Thanks for making the PR, really appreciate it

just left a few comments

File: packages/init-xmcp/package.json (hunk 2 above)
Comment (bilune) [reply packages/init-xmcp/package.json:52]: from what I just read, you shouldn’t need to install ts globally. If you are running `npx init-xmcp` inside a project that already has typescript installed, the cli should just use that version. The repo actually already [checks if typescript is listed in devDependencies](https://github.com/basementstudio/xmcp/blob/main/packages/init-xmcp/src/helpers/detect-framework.ts#L26-L36) and if it is not, it throws an error
so in theory it shouldn’t cause problems but definitely worth testing to be sure

File: packages/init-xmcp/src/helpers/update-tsconfig.ts (hunk 1 above)
Comment (bilune) [reply packages/init-xmcp/src/helpers/update-tsconfig.ts:4]: it seems all the imports of this package has this issue, it throws this linter error

> Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../utils/read-config-file.js'?ts(2835)

might be a good improvement to make in a separate PR, what u think?

**Review by valebearzotti — APPROVED** [review]

**Comment by valebearzotti** [comment]
Thank you for your contribution @bilune !
